name: CI Linting

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

# This workflow builds and lints the application.
# It uses the built-in GITHUB_TOKEN to release and DOES NOT require any external secrets.

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff Check
        run: ruff check src/

      - name: Ruff Format Check
        run: ruff format --check src/